apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  grafana.ini: |-
    [server]
    domain = ""
    [log]
    mode = console
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local:80
  dashboardproviders.yaml: |-
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        options:
          path: /var/lib/grafana/dashboards
        updateIntervalSeconds: 10

