apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 32000  # או תבחר פורט פנוי אחר
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
