apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chartmuseum
  template:
    metadata:
      labels:
        app: chartmuseum
    spec:
      containers:
        - name: chartmuseum
          image: chartmuseum/chartmuseum:latest
          args: ["--storage=","--port=8080"]
          ports:
            - containerPort: 8080
