replicaCount: 1

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

adminUser: admin
adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local:80

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        options:
          path: /var/lib/grafana/dashboards
        updateIntervalSeconds: 10

dashboardsConfigMaps:
  - my-grafana-dashboard
  - orders-dashboard
