apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrape-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  additional-scrape-config.yaml: |
    - job_name: 'shopnserve-api'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: shopnserve-api;http
