name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:   # optional: allows manual trigger from Actions tab

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/shop-n-serve-api:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/shop-n-serve-api:${{ github.sha }}

      - name: Tag image as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/shop-n-serve-api:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/shop-n-serve-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shop-n-serve-api:latest
